### ISSUE TITLE
Installation Error: Cannot Find 'Package.swift' file

### ISSUE THREAD

**Issue by MuneMalik** [toniremi/PolygonioSwift#1] opened 2022-04-13 18:55 UTC
_(This is my first time putting in an issue one someone else's repository that isn't on my own team, so please excuse any mistakes.)_

I tried to install `PolygonioSwift` as a package, but it keeps giving me an error.

### Steps I took:

1. Download `PolygonioSwift`
2. Go to Xcode > File > Add Packages > Add Local... 
3. Choose the folder
4. This error pops up

<img width="263" alt="Screen Shot 2022-04-13 at 1 53 29 PM" src="https://user-images.githubusercontent.com/99150021/163250325-88737c34-a04c-4fb2-b1a3-2d7cad291aa4.png">

I'm using Xcode 13, so something may have changed, but I'm not entirely sure since I started using swift recently. Also, there definitely is a `Package.swift` file in the folder.

**Comment by toniremi** [comment] 2022-04-14 00:11
You need to add the package as a dependency instead of as a local package.

Try the following instructions:

1. Copy the following url https://github.com/toniremi/PolygonioSwift
2. Go to Xcode > File > Add Packages
3. On the search bar on the top right corner paste the github repo url (https://github.com/toniremi/PolygonioSwift)
4. Select PolygonSwift from the list
5. Click on Add Package

You should have the package now added correctly on to your project.

I updated the readme to better reflect this steps.

I will now close this issue. If problem persists open a new issue.

Thanks.

**Closed as completed by toniremi** 2022-04-14 00:11 UTC

**Comment by toniremi** [comment] 2022-10-11 07:22
Hello,

I just tried it on a clean project and it works fine.

I think the problem is with adding it as a local package.

Instead you need to add directly using the github repository url as follows:

1. Copy the following url https://github.com/toniremi/PolygonioSwift
2. Go to Xcode > File > Add Packages
3. On the search bar on the top right corner paste the github repo url (
https://github.com/toniremi/PolygonioSwift)
4. Select PolygonSwift from the list
5. Click on Add Package

After this the package should be added as a dependency to your project and
you can access it without any issues.

Hope this helps. Maybe I should add more detailed steps on the readme. I'll
try to update it with these exact steps soon.
